- name: Desinstalar nginx # Desinstalar y eliminar Nginx de servidores Ubuntu
  hosts: webserver # Atacar todos los hosts definidos en el inventario
  become: yes # Escalar privilegios a root
  tasks: # Definir las tareas a ejecutar
    - name: Detener el servicio Nginx # Asegurarse de que el servicio Nginx esté detenido
      service:
        name: nginx # Nombre del servicio a gestionar
        state: stopped # Detener el servicio

    - name: Desinstalar Paquete Nginx # Desinstalar el paquete Nginx usando apt
      apt:
        name: nginx # Nombre del paquete a desinstalar
        state: absent # Asegurarse de que el paquete esté ausente